apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-backend
  template:
    metadata:
      labels:
        app: springboot-backend
    spec:
      containers:
      - name: springboot-backend
        image: springboot-backend-image:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
