name: Runner Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-runner:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Test runner
        run: |
          echo "Running on my self-hosted runner"
          kubectl config current-context
          kubectl get pods
