name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Check Kubernetes
        run: |
          kubectl config current-context
          kubectl get nodes
          kubectl get pods

      - name: Restart backend deployment
        run: |
          kubectl rollout restart deployment/employee-backend

      - name: Wait for backend rollout
        run: |
          kubectl rollout status deployment/employee-backend
